Clean up on Isle 1 for Resolvers + New PrivateCollectionResolver
wshafer/assetmanager-core pull request #25
Opened 2017-08-03 14:37 UTC by wshafer

2017-08-10 07:45 UTC, RWOverdijk requested changes
Quick scan, not a full review.

2017-08-10 07:45 UTC, RWOverdijk commented on src/Resolver/FileResolverAbstract.php
> +    protected function getHtmlAsset($filePath)
Docblock

2017-08-10 07:45 UTC, RWOverdijk commented on src/Resolver/FileResolverAbstract.php
> +    protected function getFileAsset($filePath)
Docblock

2017-08-10 07:45 UTC, RWOverdijk commented on src/Resolver/PathStackResolver.php
> +            return $asset;
Newline before return

2017-08-10 07:45 UTC, RWOverdijk commented on src/Resolver/PrivateCollectionResolver.php
> +        $collection->setTargetPath($name);
Newline between assignment and method call

2017-08-10 07:45 UTC, RWOverdijk commented on src/Resolver/PrivateCollectionResolver.php
> +     * @return \Assetic\Asset\FileAsset|\Assetic\Asset\HttpAsset|null
Newline in between docblock types

2017-08-10 07:45 UTC, RWOverdijk commented on src/Resolver/PrivateCollectionResolver.php
> +        return $asset;
Newline before return

2017-08-28 14:30 UTC, wshafer commented
Breaking this out into smaller pieces.

2017-09-21 20:37 UTC, merged